/**
 * Worker entry point: the OpenNext-generated Next.js handler for HTTP traffic,
 * plus a `scheduled` handler for the Cron Trigger (catalog sync + order sweep).
 * Configured as `main` in wrangler.jsonc.
 */
// @ts-ignore — generated by `opennextjs-cloudflare build`
import { default as nextHandler } from "./.open-next/worker.js";
import { syncCatalog } from "./src/lib/catalog";
import { AUTH_CHALLENGE, checkBasicAuth } from "./src/lib/auth";
import type { Env } from "./src/lib/env";
import { sweepOrders } from "./src/lib/orders";
import { log } from "./src/lib/util";

interface ScheduledController { cron: string; scheduledTime: number }
interface ExecutionContext { waitUntil(p: Promise<unknown>): void; passThroughOnException(): void }

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const pathname = new URL(request.url).pathname;
    if (pathname === "/admin" || pathname.startsWith("/admin/")) {
      if (!checkBasicAuth(request.headers.get("authorization"), env.ADMIN_USERNAME, env.ADMIN_PASSWORD)) {
        return new Response("Authentication required", AUTH_CHALLENGE);
      }
    }
    return nextHandler.fetch(request, env, ctx);
  },

  async scheduled(controller: ScheduledController, env: Env, ctx: ExecutionContext) {
    log("info", "cron fired", { cron: controller.cron });
    // Orders first: getting paid orders to Printify matters more than the catalog.
    ctx.waitUntil(
      (async () => {
        try {
          await sweepOrders(env);
        } catch (e) {
          log("error", "order sweep crashed", { error: String(e) });
        }
        await syncCatalog(env, "cron");
      })(),
    );
  },
};

// If you later enable OpenNext's Durable Object caching (see OpenNext docs),
// re-export its classes here, e.g.:
// export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
